# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lanx Satura
email: remi.chauvin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  © 2016 by Lanx Satura : Usman W. Chohan and Rémi Chauvin. `Castigat Ridiendo Mores` | | The Global Satire Index
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lanxsatura.github.io" # the base hostname & protocol for your site
twitter_username: lanxsatura
github_username:  lanxsatura

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
